import type { Metadata } from "next";
import Header from './layout/Header/Header'
import Footer from './layout/Footer';

import "./globals.css";
import 'animate.css';

export const metadata: Metadata = {
  title: "VINOGOURMET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: JSX.Element | JSX.Element[];
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body className="w-100 min-w-min h-screen bg-white relative overflow-hidden">
        <Header />
        <div className="flex items-center justify-center">
        </div>
        <section className='absolute bottom-0 left-0 w-screen'>
        <Footer />
        </section>
      </body>
    </html>
  );
}